colors:
  primary:
    background: '0x161616'
    foreground: '0xffffff'
  cursor:
    cursor: '0xdde1e6'
  vi_mode_cursor:
    cursor: '0xdde1e6'
  selection:
    text: '0xdde1e6'
  normal:
    black: '0x161616'
    red: '0x33b1ff'
    green: '0xff7eb6'
    yellow: '0x42be65'
    blue: '0x08bdba'
    magenta: '0x82cfff'
    cyan: '0x78a9ff'
    white: '0xdde1e6'
  bright:
    black: '0x525252'
    red: '0x33b1ff'
    green: '0xff7eb6'
    yellow: '0x42be65'
    blue: '0x08bdba'
    magenta: '0x82cfff'
    cyan: '0x78a9ff'
    white: '0xffffff'
  hints:
    start:
      foreground: '#908caa'
      background: '#1f1d2e'
    end:
      foreground: '#6e6a86'
      background: '#1f1d2e'
